# Generated by Django 4.2.9 on 2024-02-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='count',
            new_name='link_click_count',
        ),
        migrations.AddField(
            model_name='post',
            name='tag_count',
            field=models.IntegerField(default=0),
        ),
    ]
